linuxlite/litetweaks

- usr/bin/lite-tweaks
A single password entry is now required
Less dialogs
> Merged the scripts into two files

- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
https://www.linuxliteos.com/forums/developers-corner/review-set-default-browser-lite-tweak/msg27764/#msg27764
> Reviewed Set Default Browser and few others

- usr/bin/lite-tweaks-super
Thread https://www.linuxliteos.com/forums/developers-corner/lite-tweaks-locate-large-files/
> Update Locate Large Files

- usr/bin/lite-tweaks-super
- added clear memory confirmation dialog 
- fix issue where removing residual configuration files breaks multiple tasks execution
> added clear memory confirmation dialog

- usr/bin/lite-tweaks
- allow to loop
- updated buttons name
- minor text updates
> display disk usage update

- usr/bin/lite-tweaks-super
https://www.linuxliteos.com/forums/developers-corner/lite-tweaks-numlock/msg27813/#msg27813
-added loop
-remove columns headers
-changed buttons names
-update dialog size
-added contextual status
-removed unnecessary confirmation dialogs
> updated Numlock

- usr/bin/lite-tweaks-super
- updated dialogs
- renamed Cancel button
- added loop on removal cancelation
- minor wording updates
- better listing of selected kernels for removal
> updated Kernel Removal tweak

- usr/bin/lite-tweaks
- wording and interface adjustments for Default Web Browser tweak
> adjustments

- usr/bin/lite-tweaks-super
- add additional checks to prevent overwriting
/etc/lightdm/lightdm.conf unnecessarily and prompt.
- prompt user when no option has been selected
> numlock tweak updates

- usr/bin/lite-tweaks-super
Numlock
- removed unnecessary dialogs
- add status checks before writing settings
Preload
- add status checks before writing settings
Manage Save Session
- add status checks before writing settings
> tweaks updated

- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
define run icon for Lite Tweaks progress dialog
> Lite Tweaks progress dialog

- usr/bin/lite-tweaks
- set default browser in Preferred Applications Xfce
> update default browser settings

- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
> add zRAM tweak

- usr/bin/lite-tweaks-super
> fix wrong variable name

- usr/bin/lite-tweaks
Remove shouting in Default browser lite tweak
> minor wording adjustment

- usr/bin/lite-tweaks-super
Corrects manage save sessions and login/logout options tweaks defaults
> fix defaults

- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
- Fix Manage Save Session and Login & Logout Options so that they don't cancel subsequent tasks when multiple tweaks are selected for execution and the Exit button is clicked.
- Update text uniformly across tweaks
- Add check before editing numlock settings. Only write settings if needed
- Add check before editing login options. Only write settings if needed
- Add check before editing logout options. Only write settings if needed
> minor update

- usr/bin/lite-tweaks-super
Update text uniformly across tweaks:
numlock, preload,zram
> ui updates

- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
ask to logout after changes in Login & Logout Options and Hibernate,
Suspend tweaks.
> ask to logout

- usr/bin/lite-tweaks-super
crude logout fix on Login and Logout Options
> logout fix

- usr/bin/lite-tweaks-super
increase window height size for Manage Saved sessions tweak not to show
scrollbar inside dialog.
> minor window size adjustment

- usr/bin/lite-tweaks-super
manage save session ask logout
add a function to use for all tweaks needing to ask for logout
> Ask for logout - Manage Save Session

- usr/bin/lite-tweaks-super
> sync before dropping cache

- usr/bin/lite-tweaks
Added Opera browser support for Default Web Browser tweak
Added Opera browser cache clean support
> support for Opera browser

- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
- usr/share/doc/lite-tweaks/changelog
- usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_tweaks.policy
Move from gksu to pkexec
Added policyconfig
Code cleanup and minor wording changes
> added policyconfig

- usr/bin/lite-tweaks
- usr/share/doc/lite-tweaks/changelog
This reverts commit e5467864c57d3f5f5f7ef490d5db2496cbd2050c.
> revert removed column

- usr/bin/lite-tweaks
- usr/share/doc/lite-tweaks/changelog
* Don't show Package Cache task if there are no files for removal
* Don't show Thumbnails Cache task if there are no files for removal
* Don't show Log Archives task if there are no files for removal
> showing and hiding tasks

- DEBIAN/postinst
- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
- usr/share/doc/lite-tweaks/changelog
- usr/share/litemodules/dryapt
* Don't show Autoremove Packages task if there are no packages for
removal
* Bug fix - $_MYLTUSER variable should return sudoer $USER instead of
root (lite-tweak-super)
* cleanup zenity output in lite-tweaks-super
> updates autoremove packages

- DEBIAN/postinst
- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
- usr/local/sbin/xauth-cleanup
- usr/local/sbin/xauth-cleanup.desktop
- usr/share/doc/lite-tweaks/changelog
* Update Hostname tweak to not longer require rebooting or logging out
the session
* Added feature to cleanup old xauth in .Xauthority after logon
* Update 'netbios name' in Samba smb.conf to match new hostname set by
Hostname tweak
> Change Hostname tweak update

- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
- usr/share/doc/lite-tweaks/changelog
Install lite firmware for 4.11.x onwards
> update kernel installer 

- usr/bin/lite-tweaks
- usr/bin/lite-tweaks-super
* added noninteractive kernel installer
* added kernel removal logging
> added noninteractive kernel installer

- usr/bin/lite-tweaks-super
- Revert Stage 1 when error occurs
- add package system repair logging
add common function for viewing and saving error log
- add tweak name on each error log header
> add Stage 1 package system repair logging
